export const SET_BREEDS = 'SET_BREEDS';
export const FETCH_BREEDS_FAILED = 'FETCH_BREEDS_FAILED';
export const LOADING_BREEDS = 'LOAD_BREEDS';

export const SET_SUBBREEDS = 'SET_SUBBREEDS';
export const FETCH_SUBBREEDS_FAILED = 'FETCH_SUBBREEDS_FAILED';
export const LOADING_SUBBREEDS = 'LOAD_SUBBREEDS';

export const SET_IMAGELINK = 'SET_IMAGELINK';
export const FETCH_IMAGELINK_FAILED = 'FETCH_IMAGELINK_FAILED';
export const LOADING_IMAGELINK = 'LOAD_IMAGELINK';